version: '3.5'

volumes:
  redis-data:

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 8090:80

  rest:
    build:
      context: ./rest
      dockerfile: Dockerfile
    container_name: rest
    restart: always
    volumes:
      - ./rest:/var/www/rest
    depends_on:
      - nginx
      - redis

  redis:
    image: redis
    restart: always
    container_name: redis
    command: redis-server
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - rest
      - socket
    environment:
      - NODE_ENV=development
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'

  socket:
    container_name: socket
    build:
      context: ./socket
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6001:6001"
    depends_on:
      - redis
    
